create table cliente (
       id bigint generated by default as identity,
        contrasenia varchar(255) not null,
        direccion varchar(255) not null,
        edad integer not null,
        estado varchar(255) not null,
        genero varchar(255) not null,
        identificacion varchar(255) not null,
        nombre varchar(255) not null,
        telefono varchar(255) not null,
        primary key (id)
    );

create table cuenta (
       id bigint not null,
        clave varchar(255) not null,
        numero varchar(255) not null,
        saldo_inicial bigint not null,
        tipo varchar(255) not null,
        cliente_id bigint,
        primary key (id)
    );

create table movimiento (
       id bigint not null,
        fecha timestamp not null,
        valor double not null,
        cuenta_id bigint,
        primary key (id)
    );

alter table cuenta 
       add constraint UK_hsp0g5b3ckv9kgikc6e85l1jb unique (numero);

alter table cuenta 
       add constraint FK4p224uogyy5hmxvn8fwa2jlug 
       foreign key (cliente_id) 
       references cliente;

alter table movimiento 
       add constraint FK4ea11fe7p3xa1kwwmdgi9f2fi 
       foreign key (cuenta_id) 
       references cuenta;